### ISSUE TITLE
allow configurable server deployments, limit which `docker compose` containers get ran by adding `profile.omgd.servers` block to clarify which and what type of `servers/` are setup in corresponding directory

### ISSUE THREAD

**Issue by newnoiseanand** [newnoiseworks/omgd#214]
ala:

```yaml
omgd:
  servers:
    host: 127.0.0.1
    services:
    - central
    - web
    - headless
```

note the move of `omgd.servers.host` from `omgd.servers.central.host` -- one should override the other if exists, only important in one template I believe

1. [x] update should adjust `docker compose up` commands, may not be testable
2. [x] ensure all old `profiles/` in examples are up to date - delete stuff taht's not needed ala `local.yml` files having a host IP (set by default in templates where it's used)
