### ISSUE TITLE
create separate `omgd.cloud.yml` file -- could privately store all cloud info, e.g. `gcp` details

### ISSUE THREAD

**Issue by newnoiseanand** [newnoiseworks/omgd#231]
this would store `gcp`, `tfsettings`, and others

```
omgd:
  gcp:
    project: your-project-id
    zone: us-east-4c
    bucket: your-generated-bucket-name
```

would need to merge with profiles on `infra` deploy and `build-clients` step. slight challenges in making hostnames work, should just need to append the profile name and that should be ok
