### ISSUE TITLE
store profile IP addresses within `omgd.cloud.yml` file, make all other profiles `git`-able

### ISSUE THREAD

**Issue by newnoiseanand** [newnoiseworks/omgd#238]
move the IP address / hostname storage of each profile to `omgd.cloud.yml`

```
omgd:
  profiles:
    staging:
      servers:
        host: 1.1.1.1
```

1. [ ] adjust storage of hosts via `infra deploy` command to write to `omgd.cloud.yml`
2. [ ] adjust `profile.go` to merge individual profile definition, should it exist, into profile, e.g. the above would read as `omgd.profiles.staging.servers.host` AND `omgd.servers.host` if the `staging.yml` file was loaded
3. [ ] ensure tests pass and builds work w/ example project
